### ISSUE TITLE
Gitter chat room

### ISSUE THREAD

**Issue by mohsen3** [commercialhaskell/jump#2]
Why don't you open a https://gitter.im/ chatroom for this project, so we can discuss our opinions, before making garbage issues?

**Comment by angerman** [comment]
Being the one who started a similar discussion on snowleopard/shaking-up-ghc#40, and knowing that most the haskell discussion already happens on irc, my recommendation is to stick with irc.

**Comment by mohsen3** [comment]
Cool! Thanks. I didn't know about the irc channel.

**Comment by snoyberg** [comment]
Agreed with @angerman here, and thank you both for the input.
